import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:walk_it_up/constants.dart';
import 'package:walk_it_up/data/database/dao/alarm_set/alarm_set_dao.dart';
import 'package:walk_it_up/data/database/dao/regular_alarm/regular_alarms_dao.dart';
import 'package:walk_it_up/data/database/tables/alarm_tables.dart';
import 'package:walk_it_up/data/database/type_converter/enum_list_converter.dart';
import 'package:walk_it_up/data/database/type_converter/equal_list.dart';
import 'package:walk_it_up/data/model/weekdays.dart';

part 'alarm_database.g.dart'; // This will be generated by drift

@DriftDatabase(
    tables: [RegularAlarms, AlarmSets, RecurringAlarms],
    daos: [RegularAlarmsDao, AlarmSetDao])
class AlarmDatabase extends _$AlarmDatabase {
  bool isUnderTest = false;

  AlarmDatabase() : super(_openConnection());

  AlarmDatabase.test(QueryExecutor executor) : super(executor) {
    isUnderTest = true;
  }

  static QueryExecutor _openConnection() {
    return driftDatabase(name: ALARM_DATABASE);
  }

  @override
  int get schemaVersion => 5;

  @override
  MigrationStrategy get migration =>
      MigrationStrategy(beforeOpen: (details) async {
        // Prepopulate the db on first creation and in case it's not
        // for testing
        if (details.wasCreated && !isUnderTest) {
          final date = DateTime.now();
          into(regularAlarms).insert(
            RegularAlarmsCompanion.insert(
              audioPath: 'assets/perfect_alarm.mp3',
              time: DateTime(date.year, date.month, date.day, 10, 0),
            ),
          );

          final alarmSetId = await into(alarmSets).insert(
            AlarmSetsCompanion.insert(
              audioPath: 'assets/perfect_alarm.mp3',
              startTime: DateTime(date.year, date.month, date.day, 9, 0),
              endTime: DateTime(date.year, date.month, date.day, 12, 0),
              daysOfWeek: Value(EqualList([
                Weekday.monday,
                Weekday.tuesday,
                Weekday.wednesday,
              ])),
              intervalBetweenAlarms: 60,
            ),
          );

          final recurringAlarmList = [
            RecurringAlarmsCompanion.insert(
              alarmSetId: alarmSetId,
              time: DateTime(date.year, date.month, date.day, 10, 0),
            ),
            RecurringAlarmsCompanion.insert(
              alarmSetId: alarmSetId,
              time: DateTime(date.year, date.month, date.day, 11, 0),
            ),
            RecurringAlarmsCompanion.insert(
              alarmSetId: alarmSetId,
              time: DateTime(date.year, date.month, date.day, 12, 0),
            ),
          ];

          batch((batch) {
            batch.insertAll(recurringAlarms, recurringAlarmList);
          });
        }
        // Turned off by default in sqlite 3, needs to be manually activated
        await customStatement('PRAGMA foreign_keys = ON');
      });
}
